{% set name = "libva" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-{{ version }}.tar.gz
  sha256: 7bca8c8a854653e15e602f243e2452e84e4b454b26549bf80a932ab29d7d6b21

build:
  skip: true  # [not linux]
  number: 0
  # Pretty good forward compatibility
  # https://abi-laboratory.pro/index.php?view=timeline&l=libva
  run_exports:
    - {{ pin_subpackage('libva', max_pin='x') }}
  # https://01.org/linuxgraphics/documentation/build-guide-0
  script:
    - touch Makefile.am
    - touch */Makefile.am
    - touch */*/Makefile.am
    - touch configure.ac
    - ./autogen.sh --prefix=$PREFIX
    - make -j$(nproc) install

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libdrm
    - mesalib
  run:
    - mesalib

test:
  commands:
    - test -f $PREFIX/include/va/va.h
    - test -f $PREFIX/lib/libva.so
    - test -f $PREFIX/lib/libva.so.2
    - test -f $PREFIX/lib/pkgconfig/libva.pc
    - test -f $PREFIX/lib/pkgconfig/libva-drm.pc
    - test -f $PREFIX/lib/libva-drm.so
    - test -f $PREFIX/lib/libva-drm.so.2

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends
    for each supported hardware vendor.

extra:
  recipe-maintainers:
    - hmaarrfk
