{% set name = "libva" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-{{ version }}.tar.gz
  sha256: 6b7ec7d4fa204dad3f266450981f1f0892400c03afd3e00ac11f8ccade5aaaa1

build:
  skip: true  # [not linux]
  number: 1
  # Pretty good forward compatibility
  # https://abi-laboratory.pro/index.php?view=timeline&l=libva
  run_exports:
    - {{ pin_subpackage('libva', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    - libdrm
    # Seems like they want to install mesalib, but conda-forge complains of
    # overlinking if we include it as a run requirement
    # - mesalib

test:
  commands:
    - test -f $PREFIX/include/va/va.h
    - test -f $PREFIX/lib/libva.so
    - test -f $PREFIX/lib/libva.so.2
    - test -f $PREFIX/lib/pkgconfig/libva.pc
    - test -f $PREFIX/lib/pkgconfig/libva-drm.pc
    - test -f $PREFIX/lib/libva-drm.so
    - test -f $PREFIX/lib/libva-drm.so.2

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends
    for each supported hardware vendor.

extra:
  recipe-maintainers:
    - hmaarrfk
