{% set name = "libva" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-{{ version }}.tar.gz
  sha256: 67f0289944b3c39307ab0f1b7ab33de072f6e674758d2f122b51616c3d7b115b

build:
  skip: True  # [not linux]
  number: 0
  # https://abi-laboratory.pro/index.php?view=timeline&l=libva
  run_exports:
    - {{ pin_subpackage('libva', max_pin='x.x') }}
  # https://01.org/linuxgraphics/documentation/build-guide-0
  script:
    - ./autogen.sh --prefix=$PREFIX
    - make -j$(nproc) install

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libdrm
    - mesalib
  run:
    - mesalib

test:
  commands:
    - test -f $PREFIX/include/va/va.h
    - test -f $PREFIX/lib/libva.so
    - test -f $PREFIX/lib/libva.so.2
    - test -f $PREFIX/lib/pkgconfig/libva.pc
    - test -f $PREFIX/lib/pkgconfig/libva-drm.pc
    - test -f $PREFIX/lib/libva-drm.so
    - test -f $PREFIX/lib/libva-drm.so.2

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Libva is an implementation for VA-API (Video Acceleration API)'

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends
    for each supported hardware vendor.

extra:
  recipe-maintainers:
    - hmaarrfk
