{% set name = "libva" %}
{% set version = "2.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-{{ version }}.tar.gz
  sha256: f7c3fffef3f04eb146e036dad2587d852bfb70e4926d014bf437244915ef7425

build:
  skip: true  # [not linux]
  number: 1
  # Pretty good forward compatibility
  # https://abi-laboratory.pro/index.php?view=timeline&l=libva
  run_exports:
    - {{ pin_subpackage('libva', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    - libdrm
    - xorg-libx11
    - xorg-libxext
    - xorg-libxfixes
  run:
    - xorg-libx11
    - xorg-libxext
    - xorg-libxfixes
test:
  commands:
    - test -f $PREFIX/include/va/va.h
    - test -f $PREFIX/lib/libva.so
    - test -f $PREFIX/lib/libva.so.2
    - test -f $PREFIX/lib/pkgconfig/libva.pc
    - test -f $PREFIX/lib/pkgconfig/libva-drm.pc
    - test -f $PREFIX/lib/libva-drm.so
    - test -f $PREFIX/lib/libva-drm.so.2
    - test -f $PREFIX/lib/libva-x11.so
    - test -f $PREFIX/lib/libva-x11.so.2

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)

  # The remaining entries in this section are optional, but recommended
  description: |
    VA-API is an open-source library and API specification, which provides
    access to graphics hardware acceleration capabilities for video processing.
    It consists of a main library and driver-specific acceleration backends
    for each supported hardware vendor.

extra:
  recipe-maintainers:
    - gabm
    - hmaarrfk
