appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PoczTtjTwWyRPOmSdAJycWxNbrMu6t0X73XF/Kbhhs7EtbgDvmf6hJGeY4uDZL1A1dwnK8M1yFO5QMCPZxRFFHhL0t+2CL2MX+FSbHsv4yr6Z7eWgiUSE2aqz+zgd4ijKAt2bHIS1doqS02jJOtT+WtEXXVOJec7TN8HfNpFUF/KVnkb8+2D5GTgqH9CMiqyT7lKVpl2fOEPLhyCh7n0TYRgLllB6NW3igaK04RmDNx0sUS9La/CGkZ1rs56wz+MjVdAIaWq1SPlBwPj+ARoe/+c2Z9oDlY/Q2+rxEUFln5CCOwkgjHR7GMvDJ22+JjFh2yH+/o0fp7G6xe7MeBpxitsSoCDbEs7bFjRNX0pVOPSwGGPoggywtbrXwQae7raaN/Uf3mzE9gEZPa7rPY14XiAZ/K+/jlu+5Pffkqfc5r6yiCNnMaixtn2ChkfkxgWpX6VIhQ2tWHPv5ue9/KqWbGiTSk8uZV31tqyRYDvURhnJJ5KfUMtyLUfEbk8wf/RmNWTVEuRDEjda/yVaFrJ8HeENiXbm4U+8s3+DsgU/jGwgnmPW1YGpGGQyOXjt8Aiig6S+/mNlL7pJ7EHaXUIVXg89+juK17U2j5lJBd9Khpu/CoM4ECsqJeZ8niw5eupV1Ka66w4IS1jxeKxvRDMUx0vLKfCB6U9Jc9tavkQ2DA=}
